@startuml

class carnet.Page{
    + LocalDate date
    + String Titre
    + String texte
    + int numPage;
    - getTitre()
    - setTitre()
    - getTexte()
    - setTexte()
    - getDate()
    - setDate()
}

class carnet.Carnet{
    + LocalDate debut;
    + int nbPages;
    + String filePath;
    -  setData()
    - ajouterPages()
    - getPages()
    - getNewPage()
    - getNbPages()
    - getDateDeb()
    - getPath()
    - updateFromFile()
    - saveToFile()

}
class carnet.SujetObserve{
    - ArrayList<Observateur> observateurs
    + void ajouterObservateur(Observateur)
    + void notifierObservateur()
    - getObservateurs()
}


carnet.Page -- "*"carnet.Carnet

carnet.SujetObserve <|-- carnet.Carnet



controleur.Observateur "*" -- carnet.SujetObserve
controleur.ControleurPage ..|> controleur.Observateur
controleur.ControleurFirstPage ..|> controleur.Observateur
controleur.ControleurMenu ..|> controleur.Observateur
controleur.ControleurMenuPage ..|> controleur.Observateur
controleur.ControleurVisuPage ..|> controleur.Observateur


class controleur.ControleurFirstPage{
    - sortir()
    - toMenu()
}

class controleur.ControleurMenu{
    + Carnet carnet;
    + Label date;
    + Label jours;
    - initialize()
    - getCarnet()
    - sortir()
    - toFirstPage()
    - toMenu()
    - toVisuPage()
    - SaveCarnet()
}

class controleur.ControleurMenuPage{
    + Carnet carnet;
    + DatePicker date;
    + TextField jours;
    - initialize()
    - sortir()
    - toMenu()
    - toFirstPage()
    - suivant()
    - precedent()
    - saveCarnet()
    - chargerCarnet()
    - updateData()
}

class controleur.ControleurVisuPage{
    + Carnet carnet;
    + int index;
    + Label titre;
    + Label texte;
    + Label date;
    - initialize()
    - updateData()
    - sortir()
    - toMenu()
    - toFirstPage()
    - suivant()
    - precedent()
}


class controleur.ControleurPage{
    + Carnet carnet;
    + Page page;
    + int index;
    + TextField titre
    + TextField texte
    + Label date
    - initialize()
    - updateData()
    - sortir()
    - toMenu()
    - toFirstPage()
    - suivant()
    - precedent()
    - save()
    - saveCarnet()
}

interface controleur.Observateur{
    + void reagir()
}


@enduml